### ISSUE TITLE
Ducky lang layouts

### ISSUE THREAD

**Issue by RaccoonRecon** [v1nc/flipperzero-firmware#1]
### Describe the enhancement you're suggesting.

Could it be possible to add Nordic keyboards for this?

**Comment by v1nc** [comment]
I will implement loading keyboard layout files from SD card soon, so I guess you need to wait until this is finished.

**Comment by xsoft** [comment]
Hi,
due experiments with RubbyDucky Ive find out that some keyboards like Czech and Slovak are tricky to catch and implement. The best resource for you to use is here:
https://github.com/hak5/bashbunny-payloads/tree/master/languages

Im just sending you this resource, coz it can be tricky to find and test any working one if US is not your main language.

(that includes "CS" az Czech language, with QWERTZ keyboard). Nordic keyboard is there too.

https://github.com/midnitesnake/USB-Rubber-Ducky/tree/master/Encoder
Java Encoder "Hak5 Duck Encoder 2.6.3" supports also variant of keyboard like:
"cs-qwerty" and "cs-qwertz"

o.MG cables scripts are using same command "DUCKY_LANG", both are compatible
https://github.com/hak5/omg-payloads

Thanks for implementing DUCKY_LANG support.

**Comment by v1nc** [comment]
> Hi, due experiments with RubbyDucky Ive find out that some keyboards like Czech and Slovak are tricky to catch and implement. The best resource for you to use is here: https://github.com/hak5/bashbunny-payloads/tree/master/languages
> 
> Im just sending you this resource, coz it can be tricky to find and test any working one if US is not your main language.
> 
> (that includes "CS" az Czech language, with QWERTZ keyboard). Nordic keyboard is there too.
> 
> https://github.com/midnitesnake/USB-Rubber-Ducky/tree/master/Encoder Java Encoder "Hak5 Duck Encoder 2.6.3" supports also variant of keyboard like: "cs-qwerty" and "cs-qwertz"
> 
> o.MG cables scripts are using same command "DUCKY_LANG", both are compatible https://github.com/hak5/omg-payloads
> 
> Thanks for implementing DUCKY_LANG support.

Hey, thanks for your input and feedback.
I currently plan to use these keymaps: https://github.com/O-MG/keymaps
There are more languages, looks like they are more maintained and there are also 3 different Czech keymaps.
I guess they match with the one you linked, dont they?

**Comment by Bramard** [comment]
Hello,

Following the instructions provided, I added the belgian french keyboard layout here : https://github.com/Eng1n33r/flipperzero-firmware/pull/40#issue-1325131218 but I don't know if it is in the right place.

This ducky lang feature is really handy, thank you.

**Comment by RogueMaster** [comment]
Hi @Bramard, unfortunately, the PR you posted is invalid with many changes unrelated to the BE keyboard. Could you please re-PR with just the valid changes for the keyboard?

**Comment by RogueMaster** [comment]
Your PR also has no changes for a BE keyboard in it @Bramard

**Comment by Bramard** [comment]
Hello @RogueMaster 

Yep, clearly this PR is wrong sorry.
The patched files are actually in the zip archive as I was not able to create a new branch on the v1nc repo.
I patched the files from the dev branch of v1nc repo.
Shoud I create a branch of the Eng1n33r repo instead ?
Appreciate the help, thanks.

EDIT : Ok fork was allowed, my mistake. Correct PR is here : https://github.com/v1nc/flipperzero-firmware/pull/4#issue-1326151788

**Comment by v1nc** [comment]
Loading keyboard layouts from sd card was merged into upstream and will be merged to official firmware soon, so please check [this](https://github.com/dummy-decoy/flipperzero_badusb_kl) how to create the layout yourself.
